# Generated by Django 3.1.1 on 2020-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20200923_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingdetails',
            options={'verbose_name_plural': 'Billing Details'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=0),
        ),
    ]
