# Generated by Django 3.1.1 on 2020-09-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0003_auto_20200926_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.FloatField()),
                ('coupon', models.CharField(max_length=40)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.billingdetails')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
