# Generated by Django 3.1.1 on 2020-09-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_auto_20200926_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_total',
            new_name='cart_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
