# Generated by Django 3.1.1 on 2020-09-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.billingdetails'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(null=True, to='Cart.Order'),
        ),
    ]
