# Generated by Django 3.1.1 on 2020-09-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20200917_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='home',
            field=models.BooleanField(default=True),
        ),
    ]
