# Generated by Django 3.1.1 on 2020-09-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0002_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
